gi# Generated by Django 3.0.1 on 2019-12-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('app', '0001_initial'), ('app', '0002_auto_20191128_1449'), ('app', '0003_event_tribute'), ('app', '0004_greyhound_spotlight'), ('app', '0005_auto_20191129_0932'), ('app', '0006_boardmember'), ('app', '0007_auto_20191129_2235'), ('app', '0008_auto_20191210_1419'), ('app', '0009_auto_20191220_1307'), ('app', '0010_auto_20191220_1310'), ('app', '0011_auto_20191220_1350'), ('app', '0012_auto_20191220_1401'), ('app', '0013_auto_20191220_1522'), ('app', '0014_auto_20191226_1133'), ('app', '0015_auto_20191226_1156'), ('app', '0016_event_address'), ('app', '0017_auto_20191226_1205'), ('app', '0018_auto_20191226_1225'), ('app', '0019_auto_20191226_1248'), ('app', '0020_auto_20191226_1254'), ('app', '0021_event_photo')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Greyhound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('photo_path', models.CharField(max_length=255)),
                ('spotlight', models.TextField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=False)),
                ('is_cat_friendly', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5)),
                ('is_dog_friendly', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5)),
                ('is_kid_friendly', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField(null=True)),
                ('end_time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00'), ('05:30', '05:30'), ('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30')], default=1, max_length=10)),
                ('host', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('start_time', models.CharField(choices=[('12:00', '12:00'), ('12:30', '12:30'), ('01:00', '01:00'), ('01:30', '01:30'), ('02:00', '02:00'), ('02:30', '02:30'), ('03:00', '03:00'), ('03:30', '03:30'), ('04:00', '04:00'), ('04:30', '04:30'), ('05:00', '05:00'), ('05:30', '05:30'), ('06:00', '06:00'), ('06:30', '06:30'), ('07:00', '07:00'), ('07:30', '07:30'), ('08:00', '08:00'), ('08:30', '08:30'), ('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30')], default=1, max_length=10)),
                ('end_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('start_am_pm', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=2)),
                ('address', models.TextField(null=True)),
                ('photo', models.CharField(choices=[('Meet & Greet', 'media\\event_photos\\meet_n_greet.png')], max_length=255, null=True)),
            ],
        ),
    ]
