# Generated by Django 3.0.1 on 2019-12-27 18:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_squashed_0021_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmember',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.CharField(choices=[('media\\event_photos\\meet_n_greet.png', 'Meet & Greet')], max_length=255, null=True),
        ),
    ]
