# Generated by Django 2.2.7 on 2019-11-28 19:49

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [

    ]
