# Generated by Django 3.0.1 on 2019-12-29 18:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191227_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreyPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('grey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Greyhound')),
            ],
        ),
    ]
