# Generated by Django 3.0.1 on 2019-12-29 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191229_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GreyPhotos',
            new_name='GreyPhoto',
        ),
    ]
