# Generated by Django 2.2.7 on 2019-11-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_greyhound_spotlight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greyhound',
            old_name='spotlight',
            new_name='is_spotlight',
        ),
    ]
