# Generated by Django 2.2.7 on 2019-11-30 03:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_boardmember'),
    ]

    operations = [

    ]
