# Generated by Django 2.2.7 on 2019-11-30 03:35

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmember',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_board_member_image_path),
        ),
        migrations.AlterField(
            model_name='greyhound',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.get_greyhound_image_path),
        ),
    ]
