# Generated by Django 3.0 on 2019-12-10 19:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191129_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardmember',
            old_name='status',
            new_name='title',
        ),
        migrations.AddField(
            model_name='greyhound',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='greyhound',
            name='is_cat_friendly',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5),
        ),
        migrations.AddField(
            model_name='greyhound',
            name='is_dog_friendly',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5),
        ),
        migrations.AddField(
            model_name='greyhound',
            name='is_kid_friendly',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('MAYBE', 'Maybe')], default='YES', max_length=5),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='greyhound',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
