# Generated by Django 3.0.1 on 2019-12-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20191226_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='greyhound',
            old_name='is_spotlight',
            new_name='spotlight',
        ),
    ]
