# Generated by Django 3.0.1 on 2019-12-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20191226_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greyhound',
            name='spotlight',
            field=models.TextField(blank=True, null=True),
        ),
    ]
