# Generated by Django 3.0.1 on 2019-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191226_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='photo',
            field=models.CharField(choices=[('Meet & Greet', 'media\\event_photos\\meet_n_greet.png')], max_length=255, null=True),
        ),
    ]
